# default configuration
baseURL = "/"
languageCode = "en-us"
summaryLength = "10"
theme = "kross-hugo"
title = "Soin à 4 mains."

# css plugins
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/slick/slick.css"
[[params.plugins.css]]
link = "plugins/themify-icons/themify-icons.css"


# js plugin
[[params.plugins.js]]
link = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/slick/slick.min.js"
[[params.plugins.js]]
link = "plugins/shuffle/shuffle.min.js"
[[params.plugins.js]]
link = "plugins/google-map/map.js"


# menu
[[menu.main]]


[[menu.main]]
URL = "blog"
name = "(Curiosités)"
weight = 1

# default parameters
[params]
home = "[Le soin]"
logo = ""
# theme color
theme_color = "#7e3c80"
# contact info
phone = "06 78 78 65 56"
email = "magali-et-lucie@soinà4mains.eu"
address = "Avenue Gaston Cabannes 33270 Floirac"
# meta description
author = "Magali De Bortoli, Lucie Castets"
description = "Dans la région de Bordeaux, Magali De Bortoli, Lucie Castets pratiquent une forme singulière : le soin énergétique à 4 mains."
# google analytics
google_analytics_id = "" # Your ID
# copyright
copyright = "Copyleft &copy; 2020 - [Les Éthers Fertiles](https://lesethersfertiles.eu/)"


# preloader
[params.preloader]
enable = true
preloader = "images/preloader.gif" # use png, jpg, svg or gif format

# contact
[params.contact]
enable = true
form_action = "#" # contact form works with : https://formspree.io

# google map
[params.map]
enable = false
gmap_api = "https://maps.googleapis.com/maps/api/js?key=&#038;types=(cities)&#038;libraries=places&#038;language=en"
map_latitude = "51.5223477"
map_longitude = "-0.1622023"
map_marker = "images/marker.png"

# social site
[[params.social]]
icon = "ti-facebook"
URL = "#"

[[params.social]]
icon = "ti-instagram"
URL = "#"

[[params.social]]
icon = "ti-dribbble"
URL = "#"

[[params.social]]
icon = "ti-twitter-alt"
URL = "#"
