# default configuration
baseURL = "/"
languageCode = "en-us"
summaryLength = "10"
theme = "kross-hugo"
title = "Soin à 4 mains"

# css plugins
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/slick/slick.css"
[[params.plugins.css]]
link = "plugins/themify-icons/themify-icons.css"


# js plugin
[[params.plugins.js]]
link = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/slick/slick.min.js"
[[params.plugins.js]]
link = "plugins/shuffle/shuffle.min.js"
#[[params.plugins.js]]
#link = "plugins/google-map/map.js"


# menu

[[menu.main]]
URL = "blog"
name = "Curiosités >"
weight = 1

# default parameters
[params]
home = "Le soin >"
logo = ""
# theme color
theme_color = "#af0bc1"
# contact info
phone = "06 52 17 82 20 <br> (Lucie Castet)"
email = "reservation@soin-4mains.eu "
address = "Avenue Gaston Cabannes 33270 Floirac"
# meta description
author = "Magali De Bortoli, Lucie Castet"
description = "Dans la région de Bordeaux, Magali De Bortoli, Lucie Castet pratiquent une forme singulière de bien-être physiologique : le soin énergétique à 4 mains."
# copyright
copyright = "Copyleft &copy; 2020 - [Les Éthers Fertiles](https://lesethersfertiles.eu/)"


# preloader
#[params.preloader]
# enable = true
# preloader = "images/preloader.gif" # use png, jpg, svg or gif format

# contact
#[params.contact]
# enable = true
# form_action = "#" # contact form works with : https://formspree.io

[markup.goldmark.renderer]
unsafe = true
